<?php

/**
 * JobeetJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Vladimir Kuprienko
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobeetJob extends BaseJobeetJob
{
    /**
     * Returns slug for company field.
     *
     * @return string
     */
    public function getCompanySlug()
    {
        return Jobeet::slugify($this->getCompany());
    }

    /**
     * Returns slug for position field.
     *
     * @return string
     */
    public function getPositionSlug()
    {
        return Jobeet::slugify($this->getPosition());
    }

    /**
     * Returns slug for location field.
     *
     * @return string
     */
    public function getLocationSlug()
    {
        return Jobeet::slugify($this->getLocation());
    }

    /**
     * @inheritdoc
     */
    public function save(Doctrine_Connection $conn = null)
    {
        if ($this->isNew() && !$this->getExpiresAt()) {
            $now = $this->getCreatedAt()
                ? $this->getDateTimeObject('created_at')->format('U')
                : time();
            $this->setExpiresAt(date('Y-m-d h:i:s', $now + 86400 * sfConfig::get('app_get_active_days')));
        }

        parent::save($conn);
    }
}
