<?php

/**
 * JobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Vladimir Kuprienko
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobeetCategory extends BaseJobeetCategory
{
    /**
     * Returns collection of category with active jobs.
     *
     * @param int $max Categories limit.
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function getActiveJobs($max = 10)
    {
        return $this->getActiveJobsQuery()
            ->limit($max)
            ->execute();
    }

    /**
     * Returns count of categories with active jobs.
     *
     * @return mixed
     */
    public function countActiveJobs()
    {
        return $this->getActiveJobsQuery()->count();
    }

    /**
     * Prepare query for getting categories with active jobs.
     *
     * @return Doctrine_Query
     */
    public function getActiveJobsQuery()
    {
        $q = Doctrine_Query::create()
            ->from('JobeetJob j')
            ->where('j.category_id = ? ', $this->getId());

        return Doctrine_Core::getTable('JobeetJob')->addActiveJobsQuery($q);
    }
}
