<?php

/**
 * JobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetJob');
    }

    /**
     * Handles request.
     *
     * @param Doctrine_Query $q
     * @return JobeetJob
     */
    public function retrieveActiveJob(Doctrine_Query $q)
    {
        return $this->addActiveJobsQuery($q)->fetchOne();
    }

    /**
     * Returns collection of active jobs.
     *
     * @param Doctrine_Query|null $q
     * @return Doctrine_Collection
     * @throws Doctrine_Query_Exception
     */
    public function getActiveJobs(Doctrine_Query $q = null)
    {
        return $this->addActiveJobsQuery($q)->execute();
    }

    /**
     * Returns active jobs count.
     *
     * @param Doctrine_Query|null $q
     * @return mixed
     */
    public function countActiveJobs(Doctrine_Query $q = null)
    {
        return $this->addActiveJobsQuery($q)->count();
    }

    /**
     * Prepare query for getting active jobs.
     *
     * @param Doctrine_Query|null $q
     * @return Doctrine_Query
     */
    public function addActiveJobsQuery(Doctrine_Query $q = null)
    {
        if (null === $q) {
            $q = $this->createQuery('j');
        }

        $alias = $q->getRootAlias();

        $q->andWhere($alias . '.expires_at > ?', date('Y-m-d h:i:s', time()))
            ->addOrderBy($alias . '.expires_at DESC');

        return $q;
    }
}